class_name CombatFeelConfig
extends RefCounted

const ATTACK_BUFFER_SECONDS := 0.45
const COMMAND_RETARGET_GRACE_SECONDS := 0.22

const MOVEMENT_SMOOTHING_CATCH_UP_SPEED := 18.0
const MOVEMENT_SMOOTHING_MAX_OFFSET := 0.70
const MOVEMENT_SMOOTHING_RESET_DISTANCE := 1.50
const MOVEMENT_SMOOTHING_SETTLE_EPSILON := 0.01

const MELEE_LUNGE_DISTANCE := 0.16
const MELEE_LUNGE_RECOVERY_SECONDS := 0.14
const MELEE_LUNGE_SETTLE_EPSILON := 0.01
